/**
 * High-recall product-candidate PROPOSAL with deterministic VERIFICATION.
 *
 * Why this exists: `extractDrugMentions` in extract.ts is a set of regexes. It
 * catches KB brands, `your <Name> product(s)` possessives and quoted spans, and
 * it misses everything else — products named in running prose, second and third
 * products in a list, product lines introduced with "including ...".
 *
 * The design constraint from the README still holds: **no span in the output is
 * ever generated by a model.** So this module splits the job in two:
 *
 *   1. PROPOSE  — a cheap generative model reads the letter and proposes names.
 *                 It is asked for recall, not precision. Its output is untrusted.
 *   2. VERIFY   — `verifyProposals` keeps a proposal only if the name occurs
 *                 verbatim in the letter, and replaces the model's string with
 *                 the exact substring taken from the letter itself.
 *
 * Step 2 is pure and unit-tested offline; step 1 is the only part that touches
 * the network. A hallucinated name cannot survive step 2, and a name that does
 * survive is, by construction, a slice of the letter — so Jev still only ever
 * chooses among spans that FDA wrote.
 */

import { generateText, Output } from "ai";
import { z } from "zod";
import type { Candidate } from "./types.js";

/**
 * Default proposer: inexpensive, fast, and reachable on this project's gateway
 * plan. Overridable via `opts.model` or the JEV_PROPOSER_MODEL env var.
 *
 * `anthropic/claude-haiku-4.5` would be the natural pick and is the better
 * extractor, but the gateway key this repo ships with is on a tier that answers
 * 403 RestrictedModelsError for it. Set JEV_PROPOSER_MODEL on a paid key.
 *
 * Whatever you pick, it only ever *proposes*: `verifyProposals` below is what
 * decides, so a weaker model costs recall, never correctness.
 */
export const DEFAULT_PROPOSER_MODEL = "google/gemini-2.5-flash";

/** Upper bound on verified candidates returned to the caller. */
const DEFAULT_MAX_CANDIDATES = 20;

/** A proposed name is rejected outright past these bounds — real brands are short. */
const MAX_NAME_CHARS = 60;
const MAX_NAME_WORDS = 8;

export type ProposalKind = "brand_product" | "active_ingredient" | "generic_product_class";
export type ProposalRole = "subject_of_violation" | "mentioned";

/**
 * One raw, untrusted suggestion from the proposer model. `kind`/`role` are
 * optional so a weaker proposer that omits them still contributes a candidate.
 */
export interface ProductProposal {
  name: string;
  kind?: ProposalKind;
  role?: ProposalRole;
}

export interface RejectedProposal {
  name: string;
  reason: "not verbatim in letter" | "redaction placeholder" | "too long" | "duplicate";
}

export interface VerifiedProposals {
  candidates: Candidate[];
  rejected: RejectedProposal[];
}

export interface ProposeOptions {
  /** Gateway model id, e.g. "anthropic/claude-haiku-4.5". */
  model?: string;
  /** Cap on verified candidates (default 20). */
  maxCandidates?: number;
}

export interface ProposeResult extends VerifiedProposals {
  /** The model id actually used, for auditing. */
  model: string;
}

// ---------------------------------------------------------------------------
// Verification (pure — no network, unit-tested in propose.test.ts)
// ---------------------------------------------------------------------------

/**
 * Single-character folds applied before matching. Every entry maps one code
 * point to exactly one ASCII character so the index map below stays 1:1.
 */
const CHAR_FOLD: Record<string, string> = {
  "‘": "'", // ' left single quote
  "’": "'", // ' right single quote / apostrophe
  "‚": "'",
  "‛": "'",
  "′": "'", // prime
  "“": '"', // " left double quote
  "”": '"', // " right double quote
  "„": '"',
  "‟": '"',
  "″": '"', // double prime
  "«": '"',
  "»": '"',
  "‐": "-", // hyphen
  "‑": "-",
  "‒": "-",
  "–": "-", // en dash
  "—": "-", // em dash
  "―": "-",
  "−": "-", // minus sign
};

function isSpace(ch: string): boolean {
  return ch === " " || /\s/.test(ch);
}

/**
 * Normalised view of a string plus an index map back into the original, so a
 * match found in normalised space can be reported as an exact original span.
 *
 * Normalisation = fold curly quotes/dashes, collapse each whitespace run to one
 * space. Case is preserved (case folding happens at match time).
 */
interface IndexedText {
  norm: string;
  /** Original index where normalised character i starts. */
  starts: number[];
  /** Original index just past where normalised character i ends. */
  ends: number[];
}

function indexText(text: string): IndexedText {
  const chars: string[] = [];
  const starts: number[] = [];
  const ends: number[] = [];
  let i = 0;
  while (i < text.length) {
    const ch = text[i]!;
    if (isSpace(ch)) {
      const runStart = i;
      while (i < text.length && isSpace(text[i]!)) i++;
      chars.push(" ");
      starts.push(runStart);
      ends.push(i);
      continue;
    }
    chars.push(CHAR_FOLD[ch] ?? ch);
    starts.push(i);
    ends.push(i + 1);
    i++;
  }
  return { norm: chars.join(""), starts, ends };
}

/** Fold + collapse a proposed name, and shed wrapping quotes/punctuation. */
function normalizeName(name: string): string {
  let out = "";
  for (const ch of name) out += isSpace(ch) ? " " : (CHAR_FOLD[ch] ?? ch);
  return out
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^["'“”‘’]+|["'“”‘’]+$/g, "")
    .replace(/[.,;:]+$/, "")
    .trim();
}

/** Any (b)(4)-style FDA redaction marker. */
const REDACTION_RE = /\(\s*b\s*\)\s*\(\s*\d+\s*\)/i;

/**
 * Locate `needle` in the letter and return the offsets of the EXACT original
 * span. Case-sensitive first; on a miss, case-insensitive — and then the
 * letter's own casing and spacing win, never the model's.
 */
function findSpanOffsets(indexed: IndexedText, needle: string): [number, number] | null {
  if (!needle) return null;
  let at = indexed.norm.indexOf(needle);
  if (at < 0) at = indexed.norm.toLowerCase().indexOf(needle.toLowerCase());
  if (at < 0) return null;
  const start = indexed.starts[at];
  const end = indexed.ends[at + needle.length - 1];
  if (start === undefined || end === undefined) return null;
  return [start, end];
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * Deterministic gate between the proposer and the candidate set.
 *
 * A proposal survives only if its name occurs verbatim in `text` (after folding
 * whitespace and curly quotes). The resulting Candidate carries the substring
 * taken from the letter — not the string the model typed.
 */
export function verifyProposals(text: string, proposals: ProductProposal[]): VerifiedProposals {
  const indexed = indexText(text);
  const candidates: Candidate[] = [];
  const rejected: RejectedProposal[] = [];
  const seen = new Set<string>();

  for (const p of proposals) {
    const raw = typeof p?.name === "string" ? p.name : "";
    const needle = normalizeName(raw);

    if (REDACTION_RE.test(raw)) {
      rejected.push({ name: raw, reason: "redaction placeholder" });
      continue;
    }
    if (needle.length > MAX_NAME_CHARS || needle.split(" ").length > MAX_NAME_WORDS) {
      rejected.push({ name: raw, reason: "too long" });
      continue;
    }

    const offsets = needle ? findSpanOffsets(indexed, needle) : null;
    if (!offsets) {
      rejected.push({ name: raw, reason: "not verbatim in letter" });
      continue;
    }

    // The letter's own span, character for character.
    const exact = text.slice(offsets[0], offsets[1]);
    const key = normalizeName(exact).toLowerCase();
    if (seen.has(key)) {
      rejected.push({ name: raw, reason: "duplicate" });
      continue;
    }
    seen.add(key);

    const kind: ProposalKind = p.kind ?? "brand_product";
    const role: ProposalRole = p.role ?? "mentioned";
    candidates.push({
      id: `drug_llm_${slug(exact)}`,
      text: `${exact} — named in the letter (${kind}, ${role})`,
      payload: {
        source: "letter-text",
        name: exact,
        kind,
        role,
        proposer: "llm-verified",
      },
    });
  }

  return { candidates, rejected };
}

// ---------------------------------------------------------------------------
// Proposal (one structured-output call through the AI Gateway)
// ---------------------------------------------------------------------------

const proposalSchema = z.object({
  products: z
    .array(
      z.object({
        name: z
          .string()
          .describe(
            "The product name copied EXACTLY as it appears in the letter, character for character. " +
              "Shortest span that is the name itself.",
          ),
        kind: z.enum(["brand_product", "active_ingredient", "generic_product_class"]),
        role: z.enum(["subject_of_violation", "mentioned"]),
      }),
    )
    .describe("Every product/brand/drug/API name that is a subject of this letter."),
});

const SYSTEM_PROMPT = [
  "You extract product names from FDA regulatory letters.",
  "",
  "You never invent, translate, correct, expand or abbreviate text. Every `name` you output",
  "must be copyable out of the letter character for character — a downstream deterministic",
  "check discards anything that is not a literal substring of the letter, so paraphrasing",
  "silently loses the candidate.",
].join("\n");

const TASK_PROMPT = [
  "List EVERY product, brand, drug, biologic, dietary supplement, beverage, device or active",
  "pharmaceutical ingredient name that is a SUBJECT of this letter: things the firm makes,",
  "markets or distributes, and things FDA discusses as violative, adulterated, misbranded or",
  "unapproved. Optimise for RECALL — a later deterministic step removes anything that is not",
  "literally in the letter, so include a borderline name rather than dropping it.",
  "",
  "Look in running prose, not just in quotes. Product names appear in constructions like",
  '"your X product", "including X, Y, and Z", "you manufacture ... X", "your X and Y products".',
  "When a sentence lists several products, output EACH of them separately.",
  "",
  "For each product report:",
  "- name: the exact substring from the letter, and the SHORTEST span that is the name itself.",
  "    * Drop a trailing 'product' / 'products' that the letter appends after the name.",
  "    * Drop trailing flavour lists, pack sizes, container descriptions and dosage-form words",
  "      that follow the name (e.g. a name followed by 'Strawberry, Lemon Lime, and Orange",
  "      flavored products' is just the name).",
  "    * But KEEP words that are genuinely part of the name, including words like 'Beverage',",
  "      'Tea' or 'Gel' when the brand name itself contains them.",
  "    * Keep the letter's own capitalisation, spelling and punctuation.",
  "- kind: brand_product | active_ingredient | generic_product_class",
  "- role: subject_of_violation if FDA treats it as violative/unapproved/adulterated/misbranded,",
  "    otherwise mentioned.",
  "",
  "NEVER output:",
  "- redaction placeholders such as (b)(4), or any name containing one;",
  "- company, firm, corporate entity or person names;",
  "- organism, genus or species names;",
  "- statutes, regulations, CFR citations, FDA form names, guidance titles, office names;",
  "- website addresses or page titles;",
  "- marketing slogans or quoted advertising claims (these are claims ABOUT a product, not",
  "  the product's name) — including all-caps advertising lines.",
  "",
  "If the letter names no product in the clear (for example because every product name is",
  "redacted), return an empty list rather than guessing.",
  "",
  "LETTER:",
  "-----",
].join("\n");

/**
 * Propose product candidates with a generative model, then verify every name
 * against the letter text. Only verified spans come back as Candidates.
 */
export async function proposeProductCandidates(
  text: string,
  opts: ProposeOptions = {},
): Promise<ProposeResult> {
  const model = opts.model ?? process.env.JEV_PROPOSER_MODEL ?? DEFAULT_PROPOSER_MODEL;
  const maxCandidates = opts.maxCandidates ?? DEFAULT_MAX_CANDIDATES;

  const { output } = await generateText({
    model,
    temperature: 0,
    system: SYSTEM_PROMPT,
    prompt: `${TASK_PROMPT}\n${text}\n-----`,
    output: Output.object({
      schema: proposalSchema,
      name: "product_candidates",
      description: "Product names that are subjects of the FDA letter.",
    }),
  });

  const proposals: ProductProposal[] = output?.products ?? [];
  const verified = verifyProposals(text, proposals);

  return {
    candidates: verified.candidates.slice(0, maxCandidates),
    rejected: verified.rejected,
    model,
  };
}
